services:
  postgres:
    container_name: swe-amora-dev
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  webnet:
