"""empty message

Revision ID: 5f3ed1146f47
Revises: 
Create Date: 2024-12-09 14:06:03.797396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3ed1146f47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('reason', sa.String(), nullable=True))
    op.drop_index('ix_properties_property_name', table_name='properties')
    op.create_unique_constraint(None, 'properties', ['property_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='unique')
    op.create_index('ix_properties_property_name', 'properties', ['property_name'], unique=False)
    op.drop_column('properties', 'reason')
    op.drop_column('properties', 'approved')
    # ### end Alembic commands ###
