"""change atribute name

Revision ID: 9bc80907d76e
Revises: d717c6178882
Create Date: 2024-12-09 16:39:01.109588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc80907d76e'
down_revision: Union[str, None] = 'd717c6178882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_value_in_cents', sa.Integer(), nullable=True))
    op.drop_column('properties', 'property_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'property_value_in_cents')
    # ### end Alembic commands ###
