"""remove unique property name

Revision ID: d717c6178882
Revises: 5f3ed1146f47
Create Date: 2024-12-09 15:33:17.527575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd717c6178882'
down_revision: Union[str, None] = '5f3ed1146f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_property_name_key', 'properties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('properties_property_name_key', 'properties', ['property_name'])
    # ### end Alembic commands ###
